pages/urls.py
from django.urls import path
from pages.views import ContactUsView, AboutUsView

app_name="pages"
urlpatterns = [
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
]

products/urls.py
from django.urls import path
from products.views import ProductListView, ProductDetailView

app_name="products"
urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('detail/<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

vishmedi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('accounts/', include('allauth.urls')), 
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models


class Feedback(models.Model):
    name = models.CharField(max_length=200, help_text="Name of the sender")
    email = models.EmailField(max_length=200)
    telephone = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Feedback"

    def __str__(self):
        return self.name + "-" + self.email

products/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify
from django.urls import reverse
from django.db.models.signals import post_save, pre_save
from vishmedi.utils import unique_slug_generator, get_filename_ext
import random

def image_upload_to(instance, filename):
    slug = instance.slug
    random_name = random.randint(1, 391541656)
    basename, file_extension = get_filename_ext(filename)
    new_file_name = f"{slug}-{random_name}{file_extension}"
    return f"products/{slug}/{new_file_name}"
    

def facebook_image_upload_to(instance, filename):
    slug = instance.slug
    random_name = random.randint(1, 391541656)
    basename, file_extension = get_filename_ext(filename)
    new_file_name = f"{slug}-{random_name}{file_extension}"
    return f"products/facebook/{slug}/{new_file_name}"


class Product(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(decimal_places=2, blank=True, null=True, max_digits=7)
    description = RichTextUploadingField(blank=True, null=True)
    active = models.BooleanField(default=True)
    meta_description = models.TextField(blank=True, null=True)
    key_words = models.TextField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    slug = models.SlugField(blank=True, unique=True)
    product_image = models.ImageField(upload_to=image_upload_to, blank=True, null=True)
    facebook_image = models.ImageField(upload_to=facebook_image_upload_to, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_product_image(self):
        if self.product_image:
            return self.product_image.url
    
    def get_facebook_image(self):
        if self.facebook_image:
            return self.facebook_image.url

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

# generating unique slug
def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_reciever, sender=Product)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username
        

pages/forms.py
from django import forms

class FeedbackForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': "Full Name",
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': "Email Address",
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': "Phone Number",
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': "Enter Your Message",
        'rows': '5',
    }))

    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

pages/views.py
from django.shortcuts import render
from django.views.generic import View
from pages.forms import FeedbackForm
from django.core.mail import BadHeaderError, mail_admins, send_mail
from django.shortcuts import redirect
from pages.models import Feedback
from django.contrib import messages


class AboutUsView(View):
    def get(self, *args, **kwargs):
        return render(self.request, template_name="pages/about_us.html")


class ContactUsView(View):
    def get(self, *args, **kwargs):
        form = FeedbackForm()
        context = {
            'form': form
        }
        return render(self.request, template_name="pages/contact_us.html", context=context)

    def post(self, *args, **kwargs):
        form = FeedbackForm(self.request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            phone = form.cleaned_data.get("phone")
            message = form.cleaned_data.get("message")
            
            feedback = Feedback.objects.create(
                name=name,
                email=email,
                telephone=phone,
                message=message,
            )
            header = f"You have a feedback from {name} {email}"
            mail_admins(header, message)

            customer_subject = "Thank You For Contacting Us"
            customer_message = f"Dear {name}, \n\n Thank you so much for contacting us. We have recieved Your Email. Our Agents will take an action as soon as possible. \n\n\n Thank You, \n VishMedi Care "
            try:
                send_mail(
                    customer_subject,
                    customer_message,
                    "vishmedicare@gmail.com",
                    [email],
                    fail_silently=True
                )
            except BadHeaderError:
                return redirect('pages:feedback')
            messages.success(self.request, "Your Message has been recieved")
            print(name, email, phone, message)
        return redirect("pages:contact-us")

products/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from products.models import Product


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all().order_by('timestamp')
        context['products'] = products
        return context

class ProductDetailView(DetailView):
    model = Product
    

users/views.py
from django.shortcuts import render

# Create your views here.

pages/templates/pages/about_us.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}
About Us | VishMedi.com
{% endblock head_title %}

{% block meta_description %}
We’re a company that focusses on manufacturing and distributing high-quality medical goods to the
market to enrich the quality of the health sector.
{% endblock %}

{% block keywords %}
Vishmedi, Vish Medi Care
{% endblock %}


{% block extrastyle %}
<meta name="robots" content="all">
<link rel="stylesheet" href="{% static 'css/Team-Boxed.css' %}">
<link rel="stylesheet" href="{% static 'css/Bold-BS4-Jumbotron-with-Particles-js.css' %}">    

{% endblock extrastyle %}

{% block extrahead %}
<script src="{% static 'js/Bold-BS4-Jumbotron-with-Particles-js.js' %}"></script>
{% endblock extrahead %}


{% block fb_meta %}
<meta property="fb:app_id" content="2845903108859375" />
<meta property="og:title" content="VishMedi Care">
<meta property="og:type" content="website" />
<meta property="og:description" content="We’re a company that focusses on manufacturing and distributing high-quality medical goods to the market to enrich the quality of the health sector." />
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:image" content="http://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:secure_url" content="https://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:type" content="image/png" />
<meta property="og:image:alt" content="VishMedi Care" />
{% endblock %}


{% block content %}
<div class="jumbotron jumbotron-fluid jumbotron-main">
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script> 
    <script src="https://threejs.org/examples/js/libs/stats.min.js"></script>
        <div id="particles-js">
            <canvas class="particles-js-canvas-el" width="1409" height="319" style="width: 100%; height: 100%;"></canvas>
        </div>
        <div class="container center-vertically-holder" style="margin-top:-20px;">
            <div class="row center-vertically">
                <div class="col-md-8 offset-sm-0 offset-md-2 text-center" style="margin-top:100px;margin-bottom:100px;">
                    <h1>Who are We? <br><br></h1>
                    <hr style="border-top:1px;color:rgba(255,255,255,0.9);width:60%;margin:0px;margin-top:-50px;margin-bottom:10px;margin-left:20%;">
                    <p>We’re a company that focus on manufacturing and distributing high-quality medical goods to the market to enrich the quality of the health sector. The goods are manufactured on our own plants following the standard procedures and we’re 100% made in Sri Lanka. Currently our products are trusted by many distributors and hospitals island wide and our key focus is to establish a ‘Made-in-Sri Lanka’ brand in the global market. .</p>
                    <p><a class="btn btn-primary" role="button" href="#">Home</a></p>
                </div>
            </div>
        </div>
    </div>

    <div class="team-boxed">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Team </h2>
                <p class="text-center">Our team is highly specialized in researching new products in medical device industry in order to enhance quality and reduce cost of production.  We’re continuously maintaining our very own standards to give you the best both products and services. </p>
            </div>
            <div class="row people">
                <div class="col-md-6 item">
                    <div class="box">
                        
                        <h3 class="name">Vision</h3>
                        <p class="title">of the company</p>
                        <p class="description">To provide quality solutions to the medical industry at a reasonable cost by investing on continuous researches which enhance quality of life.  </p>

                    </div>
                </div>
                <div class="col-md-6 col-lg-6 item">
                    <div class="box">
                        <h3 class="name">Mission</h3>
                        <p class="title">of the company</p>
                        <p class="description">To be a well establish medical brand in the global context by providing the best equipment to customers. 
                        </p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    

pages/templates/pages/contact_us.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}
About Us | VishMedi.com
{% endblock head_title %}

{% block meta_description %}
We’re a company that focusses on manufacturing and distributing high-quality medical goods to the
market to enrich the quality of the health sector.
{% endblock %}

{% block keywords %}
Vishmedi, Vish Medi Care
{% endblock %}


{% block extrastyle %}
<meta name="robots" content="all">
<link rel="stylesheet" href="{% static 'css/Contact-Form-v2-Modal--Full-with-Google-Map.css' %}">   

{% endblock extrastyle %}

{% block extrahead %}
<script src="{% static 'js/Contact-Form-v2-Modal--Full-with-Google-Map.js' %}"></script>
{% endblock extrahead %}


{% block fb_meta %}
<meta property="fb:app_id" content="2845903108859375" />
<meta property="og:title" content="VishMedi Care">
<meta property="og:type" content="website" />
<meta property="og:description" content="We’re a company that focusses on manufacturing and distributing high-quality medical goods to the market to enrich the quality of the health sector." />
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:image" content="http://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:secure_url" content="https://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:type" content="image/png" />
<meta property="og:image:alt" content="VishMedi Care" />
{% endblock %}


{% block content %}
<div>
    <div class="container">
        <h1>Contact Information</h1>
        <hr>
        <form id="" action="" method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-12 col-md-6" id="message">
                    <h2 class="h4"><i class="fa fa-envelope"></i> Contact Us<small><small class="required-input">&nbsp;(*required)</small></small>
                    </h2>
                    <div class="form-group"><label for="id_name">Name</label><span class="required-input">*</span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user-o"></i>
                                </span>
                            </div>

                            {{form.name}}
                        </div>
                    </div>
                    <div class="form-group"><label for="from-email">Email</label><span class="required-input">*</span>
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-envelope-o"></i></span></div>
                            {{form.email}}    
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-12 ">
                            <div class="form-group"><label for="from-phone">Phone</label><span class="required-input">*</span>
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-phone"></i></span></div>
                                    {{form.phone}}    
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group"><label for="from-comments">Comments</label>
                        {{form.message}}
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col"><button class="btn btn-primary btn-block" type="reset"><i class="fa fa-undo"></i> Reset</button></div>
                            <div class="col"><button class="btn btn-primary btn-block" type="submit">Submit <i class="fa fa-chevron-circle-right"></i></button></div>
                        </div>
                    </div>
                    <hr class="d-flex d-md-none">
                </div>
                <div class="col-12 col-md-6">
                    <h2 class="h4"><i class="fa fa-location-arrow"></i> Locate Us</h2>
                    <div class="form-row">
                        <div class="col-12">
                            <div class="static-map col-12 mx-auto">

                            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7922.368941348242!2d79.949791!3d6.868486!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ae250ee317f72df%3A0x5d3e64fc4f0a3f0b!2sKalalgoda%20Rd%2C%2010230!5e0!3m2!1sen!2slk!4v1596363841751!5m2!1sen!2slk" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>

                        </div>
                    </div>
                        <div class="col-sm-6 col-md-12 col-lg-6">
                            <h2 class="h4"><i class="fa fa-user"></i> Our Info</h2>
                            <div><span><strong>VishMed</strong></span></div>
                            <div><span> <a href="mailto:Shirantha.vishmed@gmail.com">
                                Shirantha.vishmed@gmail.com
                            </a> </span></div>

                            <hr class="d-sm-none d-md-block d-lg-none">
                        </div>
                        <div class="col-sm-6 col-md-12 col-lg-6">
                            <h2 class="h4"><i class="fa fa-location-arrow"></i> Our Address</h2>
                            <div><span><strong>VishMed</strong></span></div>
                            <div><span>86/6, Meemanagoda Rd</span></div>
                            <div><span>Kalalgoda, Pannipitiya </span></div>
                            <div> <a href="tel:+94-775-794-833">+94-775-794-833</a> </div>
                            <hr class="d-sm-none">
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>


</div>
{% endblock content %}
    

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}
{{product.title}} | Edarn.com
{% endblock head_title %}

{% block meta_description %}
{{product.meta_description}}
{% endblock %}

{% block keywords %}
{{product.keywords}}
{% endblock %}

{% block extrastyle %}
<meta name="robots" content="all">
<link rel="stylesheet" href="{% static 'css/Article-Clean.css' %}">
{% endblock extrastyle %}

{% block extrahead %}

{% endblock extrahead %}

{% block content %}
<div class="article-clean mt-lg-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2 mt-lg-2">
                <div class="intro">
                    <h1 class="text-center">{{product.title}}</h1>

                    <img class="img-fluid" src="{{product.get_product_image}}">
                </div>
                <div class="text">
                    <p class="text-justify">{{product.description|safe}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

products/templates/products/product_list.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %}
Medical Store | VishMedi.com
{% endblock head_title %}

{% block meta_description %}
We’re a company that focusses on manufacturing and distributing high-quality medical goods to the
market to enrich the quality of the health sector.
{% endblock %}

{% block keywords %}
Vishmedi, Vish Medi Care
{% endblock %}

{% block extra_head %}
<meta name="robots" content="all">
{% endblock %}

{% block fb_meta %}
<meta property="fb:app_id" content="2845903108859375" />
<meta property="og:title" content="VishMedi Care">
<meta property="og:type" content="website" />
<meta property="og:description" content="We’re a company that focusses on manufacturing and distributing high-quality medical goods to the market to enrich the quality of the health sector." />
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:image" content="http://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:secure_url" content="https://{{request.get_host}}{% static 'img/logo.png' %}">
<meta property="og:image:type" content="image/png" />
<meta property="og:image:alt" content="VishMedi Care" />
{% endblock %}


{% block content %}
<div class="video-container mt-5 mt-lg-1"><video src="{% static 'video/vishmend_video.mp4' %}" preload="metadata" muted="" loop="" autoplay="" width="100%" height="auto"></video></div>


{% for product in products %}
<section>
    <div class="container product-section">
        <div class="row align-items-center">
            <div class="col-lg-6 
            {% if forloop.counter|divisibleby:2 %}
            order-lg-1
            {% else %}
            order-lg-2
            {% endif %}
                ">
                <div class="p-5">
                    <a href="{{product.get_absolute_url}}">
                        <img class="rounded img-fluid" src="{{product.get_product_image}}">
                    </a>
                </div>
            </div>
            <div class="col-lg-6 
            {% if forloop.counter|divisibleby:2 %}
            order-lg-2
            {% else %}
            order-lg-1
            {% endif %}
            ">
                <div class="p-5">
                    <a href="{{product.get_absolute_url}}">
                        <h2 class="display-4">{{product.title}}</h2>
                    </a>
                    <p>
                        {{product.description|safe}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endfor %}
    
{% endblock content %}
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="VishMedi">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% include 'base/gtm.html' %}
    <!-- SEO Meta Tags-->

     <link rel="home" href="https://vishmedi.com/" />
    <title>
        {% block head_title %}
        
        {% endblock %}
    </title>

    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link href="https://vishmedi.com{{request.path}}" rel="canonical">
    <meta name="keywords" content="{% block keywords %} {% endblock %}">
    {% block fb_meta %}{% endblock %}

    {% block extrastyle %}
    
    {% endblock extrastyle %}
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">    
    {% include 'base/css.html' %}

</head>
<body>
    {% include 'base/gtml_bottom.html' %}
    {% include 'base/nav_bar.html' %}
    {% include 'base/messages.html' %}
    {% block content %}
        
    {% endblock content %}
    {% include 'base/footer.html' %}

    <!-- extra scripts -->
    {% include 'base/js.html' %}   
    {% block extrahead %}{% endblock extrahead %} 

</body>
</html>

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

<link rel="stylesheet"
href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
<link rel="stylesheet" 
href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
<link rel="stylesheet" href="{% static 'css/Pretty-Footer.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/base/footer.html
{% load static %}

{% url 'pages:about-us' as about_us_url%}
{% url 'pages:contact-us' as contact_us_url %}

<footer>
    <div class="row">
        <div class="col-sm-6 col-md-4 footer-navigation">
            <h3>
                <img src="{% static 'img/logo.png' %}" alt="Vishmed Company Logo" style="width: 100px; height: 100px;">
                <a href="#">Vish<span>Medicals</span></a>
            </h3>
            <p class="links">
                <a href="{% url 'products:home' %}">Home</a>
                <strong>&nbsp; · </strong>
                <a href="{{about_us_url}}">About</a><strong> · </strong>
                <a href="{{contact_us_url}}">Contact</a><strong> · </strong></p>
            <p class="company-name">VishMed © 2020</p>
            <p class="company-name">Project By: 
                <a href="https://eldarn.com/">DonDevs Developers</a>
            </p>
        </div>
        <div class="col-sm-6 col-md-4 footer-contacts">
            <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                <p><span class="new-line-span">86/6, Meemanagoda Rd</span> Kalalgoda, Pannipitiya 
                </p>
            </div>
            <div><i class="fa fa-phone footer-contacts-icon"></i>
                <p class="footer-center-info email text-left"> 
                    <a href="tel:+94-775-794-833">+94-775-794-833</a>
                </p>
            </div>
            <div><i class="fa fa-envelope footer-contacts-icon"></i>
                <p> <a href="mailto:Shirantha.vishmed@gmail.com " target="_blank">
                    Shirantha.vishmed@gmail.com 
                </a></p>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 footer-about">
            <h4>About the company</h4>
            <p> We’re a company that focusses on manufacturing and distributing high-quality medical goods </p>
            <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
        </div>
    </div>
</footer>

templates/base/js.html
<!-- JS, Popper.js, and jQuery -->
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/bs-init.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

templates/base/messages.html
    <div class="col-12 col-md-6 col-lg-4 ml-auto msg-list-custom">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{% if message.tags %}{{ message.tags }} {% endif %}  position-fixed alert-dismissible fade show"
               role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
        {% endif %}
    </div>

templates/base/nav_bar.html
{% url 'pages:about-us' as about_us_url%}
{% url 'pages:contact-us' as contact_us_url %}

<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark navbar-custom" style="opacity: 1;">
    <div class="container"><a class="navbar-brand" data-bs-hover-animate="bounce" 
        href="{% url 'products:home' %}">Vish Medi Care</a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse"
            id="navbarResponsive">
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link 
                    {% if request.path == about_us_url %}
                        active
                    {% endif %}
                         " 
                        href="{{about_us_url}}">About US</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link
                        {% if request.path == contact_us_url %}
                            active
                        {% endif %}" href="{{contact_us_url}}">Contact us</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </div>
</nav>